/// <reference types="@cloudflare/workers-types" />
// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  NOTION_PAGE_ID: string;
  NOTION_ACCESS_TOKEN: string;
}

declare module '__STATIC_CONTENT_MANIFEST' {
  const manifest: string;
  export default manifest;
}
