name: Run Tests

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: "20"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: 🛫 Checkout code
        uses: actions/checkout@v7

      - name: "📦 Install pnpm"
        uses: pnpm/action-setup@v6
        with:
          version: 10.11.1

      - name: 🔧 Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔬 Run Unit Tests
        run: pnpm test
